
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_A = 6;
  public static final int UMINUS = 10;
  public static final int SUMA = 2;
  public static final int POR = 4;
  public static final int ENTRE = 5;
  public static final int EOF = 0;
  public static final int NUMERO = 11;
  public static final int ID = 8;
  public static final int IGUAL = 9;
  public static final int error = 1;
  public static final int PUNTOC = 12;
  public static final int ERRORLEX = 13;
  public static final int RESTA = 3;
  public static final int PAR_C = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "POR",
  "ENTRE",
  "PAR_A",
  "PAR_C",
  "ID",
  "IGUAL",
  "UMINUS",
  "NUMERO",
  "PUNTOC",
  "ERRORLEX"
  };
}

